apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::315069654700:role/eksctl-expense-1-nodegroup-expense-NodeInstanceRole-QpZ8MlrLGAdG
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: | #check userarn used below in AWS IAM roles
    - groups:
      - expense-pod-reader
      userarn: arn:aws:iam::637423596117:user/harish 
      username: harish
kind: ConfigMap
metadata:
  creationTimestamp: "2024-07-05T01:35:42Z"
  name: aws-auth
  namespace: kube-system
  uid: e1c1bb30-5091-48a8-bbf2-1b58a8e768fb #don't delete this... you will get this from command "kubectl get configmap aws-auth -n kube-system -o yaml"